# Generated by Django 4.1 on 2023-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
