# Generated by Django 4.1 on 2023-07-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='manager',
        ),
    ]
