# Generated by Django 4.1 on 2023-07-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_userprofileevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='users.userprofile', verbose_name='Менеджер организации'),
        ),
    ]
