# Generated by Django 4.1 on 2023-07-06 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_organisation_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер организации'),
        ),
    ]
