# Generated by Django 4.1 on 2023-07-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
