# Generated by Django 4.1 on 2023-05-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.ManyToManyField(to='events.format', verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='events.tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='event',
            name='topik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.topic', verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
