# Generated by Django 4.1 on 2023-05-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_format_event_tags_event_topik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='topik',
            new_name='topic',
        ),
    ]
