# Generated by Django 4.1 on 2023-05-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_topik_event_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(default='2023-05-31T12:00', verbose_name='Дата и время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dete_end',
            field=models.DateTimeField(default='2023-05-31T12:00', verbose_name='Дата и время окончания'),
            preserve_default=False,
        ),
    ]
