# Generated by Django 4.1 on 2023-05-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_dete_end_event_date_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
