# Generated by Django 4.1 on 2023-05-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_tags_options_alter_topic_options_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
