# Generated by Django 4.1 on 2023-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='topic',
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.ManyToManyField(to='events.topic', verbose_name='Направление'),
        ),
    ]
