# Generated by Django 4.1 on 2023-06-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_image_small_alter_event_title_and_more'),
    ]

    operations = [
    ]
