# Generated by Django 4.1 on 2023-06-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_organisation'),
        ('events', '0012_event_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation', verbose_name='Организация'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='topic',
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.ManyToManyField(to='events.topic', verbose_name='Направление'),
        ),
    ]
