# Generated by Django 4.1 on 2023-06-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_topic_event_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Партнеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название мероприятия'),
        ),
    ]
