# Generated by Django 4.1 on 2023-07-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_organizer_remove_event_topic_event_topic'),
        ('events', '0013_alter_event_partners_alter_event_title'),
    ]

    operations = [
    ]
