# Generated by Django 4.1 on 2023-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_merge_20230701_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.CharField(blank=True, max_length=200, verbose_name='Партнеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название мероприятия'),
        ),
    ]
