# Generated by Django 4.1 on 2023-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_partners_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Город проведения'),
            preserve_default=False,
        ),
    ]
