# Generated by Django 4.1 on 2023-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_partners_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='слаг'),
            preserve_default=False,
        ),
    ]
