# Generated by Django 4.1 on 2023-07-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_organisation_manager'),
        ('events', '0016_alter_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation', verbose_name='Организация'),
        ),
    ]
