name: CI

on:
  # Срабатывает при пуше или пулл реквесте в ветку dev.
  push:
    branches:    
      - dev
  pull_request:
    branches:    
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        # Запуск actions setup-python — готового скрипта 
        # для развёртывания окружения Python
        uses: actions/setup-python@v4
        with:
          # Выбор версии Python
          python-version: '3.10'

      - name: Install dependencies
        run: | 
          # обновление pip
          python -m pip install --upgrade pip 
          # установка flake8 и его плагинов
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # установка зависимостей
          pip install -r it_events/requirements.txt 

      - name: Test with flake8
        run: |
          # запуск проверки проекта по flake8
          python -m flake8 it_events/
      # - name: Test with django tests
      #   run: |
      #     # запуск тестов Django
      #     touch .env
      #     echo SECRET_KEY=secretkey >> .env
      #     echo DEBUG=True >> .env
      #     echo ALLOWED_HOSTS=localhost,127.0.0.1 >> .env
      #     echo DB_NAME=postgres >> .env
      #     echo POSTGRES_USER=postgres >> .env
      #     echo POSTGRES_PASSWORD=postgres >> .env
      #     echo DB_HOST=localhost >> .env
      #     echo DB_PORT=5432 >> .env
      #     cd it_events/
      #     python manage.py test users.tests
