name: CI

on:
  # Срабатывает при пуше или пулл реквесте в ветки main, dev, test.
  push:
    branches:    
      - main
      - dev
      - test
  pull_request:
    branches:    
      - main
      - dev
      - test

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
